simplify locale handling by using lowercase strings everywhere
mlcommons/modelbench pull request #768
Opened 2024-12-20 23:11 UTC by rogthefrog

The current locale implementation uses an enum, which is handy for validation, but it isn't used consistently throughout the code. Some functions declare a locale argument of the Locale type, but in actuality sometimes they get plain strings, so the function code has to 1) check the type 2) validate whether the string is a valid locale. The Locale object itself is just a bag of strings. 

@bkorycki, @bollacker and I discussed simplifying and using strings instead.

2025-01-03 21:13 UTC, bkorycki requested changes
I think this is a solid improvement! Thanks.

2025-01-03 21:13 UTC, bkorycki commented on src/modelgauge/tests/safe_v1.py
> +        if self.locale and self.locale != EN_US:
`self.locale` should never be None, right?

2025-01-06 18:20 UTC, rogthefrog commented on src/modelgauge/tests/safe_v1.py
> +        if self.locale and self.locale != EN_US:
That is true as long as someone doesn't set `self.locale` outside the constructor. It's a remote possibility, though, and should probably error out if someone does that, so I'll remove the guard clause.

2025-01-06 19:12 UTC, bkorycki approved these changes

2025-01-06 20:39 UTC, merged